# Generated by Django 4.2.10 on 2024-04-03 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.IntegerField(null=True)),
                ('coursename', models.CharField(max_length=100)),
                ('coursedate', models.DateField(blank=True, null=True)),
                ('coursepeople', models.CharField(max_length=100)),
                ('Avg_score', models.FloatField(default=0)),
                ('Median_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkid', models.IntegerField(null=True)),
                ('classdate', models.DateField(blank=True, null=True)),
                ('score', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[('ok', '已完成'), ('not', '未完成'), ('open', '審核中'), ('notopen', '未開放')], default='open', max_length=10)),
                ('classnumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
