# Generated by Django 4.2.10 on 2024-04-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='introduce',
            field=models.TextField(blank=True, help_text='Enter course introduce', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Avg_score',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Median_score',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursepeople',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
