# Generated by Django 4.2.10 on 2024-04-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_course_course_image_course_introduce_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmate',
            name='pkid',
        ),
        migrations.RemoveField(
            model_name='course',
            name='coursedate',
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='classmate',
            name='classnumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.course'),
        ),
    ]
