# Generated by Django 4.2.10 on 2024-04-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_remove_course_id_alter_course_coursenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='classnumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.course'),
        ),
    ]
