# Generated by Django 5.0.3 on 2024-04-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_alter_classmate_classnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='status',
            field=models.CharField(blank=True, choices=[('ok', '是'), ('not', '否')], default='open', max_length=10),
        ),
    ]
