# Generated by Django 4.2.10 on 2024-04-26 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_alter_classmate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=64)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=64)),
                ('unit_id', models.IntegerField()),
                ('unit_name', models.CharField(max_length=64)),
                ('start_date', models.DateTimeField()),
                ('training_time', models.IntegerField()),
                ('events', models.TextField()),
                ('score', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=64)),
                ('time', models.IntegerField()),
                ('score', models.IntegerField()),
                ('comment', models.CharField(max_length=500, null=True)),
                ('training_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.trainingresult')),
            ],
        ),
    ]
