# Generated by Django 5.0.3 on 2024-04-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_trainingresult_eventresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingresult',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
