# Generated by Django 4.2.10 on 2024-05-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_alter_trainingresult_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmate',
            name='unit_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classmate',
            name='unit_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
