# Generated by Django 4.2.10 on 2024-05-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_classmate_unit_id_classmate_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmate',
            name='training_id',
            field=models.IntegerField(null=True),
        ),
    ]
