# Generated by Django 4.2.10 on 2024-05-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_classmate_training_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '是'), ('1', '否'), ('2', '中離')], default='open', max_length=10),
        ),
    ]
