# Generated by Django 5.0.3 on 2024-05-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_alter_classmate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='classdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classmate',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '中離'), ('1', '成功'), ('2', '失敗')], default='open', max_length=10),
        ),
    ]
