# Generated by Django 4.2.10 on 2024-05-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0012_alter_classmate_classdate_alter_classmate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresult',
            name='course_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='unit_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
