# Generated by Django 5.0.3 on 2024-05-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='coursename',
            field=models.CharField(default='Coursename', max_length=200),
        ),
    ]
