# Generated by Django 4.2.10 on 2024-05-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='u_name',
        ),
    ]
