# Generated by Django 5.0.4 on 2024-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
